# Generated by Django 4.1.7 on 2023-02-15 22:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("main", "0001_initial"),
        ("main", "0002_alter_product_image"),
        ("main", "0003_alter_product_image"),
        ("main", "0004_alter_product_image"),
        ("main", "0005_alter_product_image"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveSmallIntegerField()),
                (
                    "image",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="media"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
