# Generated by Django 4.1.7 on 2023-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_basket_alter_product_name_basketitem_basket_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products"),
        ),
    ]
