# Generated by Django 4.1.7 on 2023-02-17 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="quantity",
        ),
    ]
