# Generated by Django 4.1.7 on 2023-02-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_basketitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Clothing", "Clothing"),
                    ("Accessories", "Accessories"),
                    ("Bathroom & Kitchen", "Bathroom And Kitchen"),
                    ("Electronics", "Electronics"),
                ],
                default="Accessories",
                max_length=30,
            ),
        ),
    ]
