# Generated by Django 4.1.7 on 2023-02-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
